"use client";

import { useEffect, useMemo, useState } from "react";
import { Database, FolderPlus, Plus, Search, Users } from "lucide-react";
import { createId, nowIso } from "@heather/core";
import type { HeatherLanguage, MemoryRecord } from "@heather/core";
import { SupabaseMemoryRepository, type ResearchProject, type Team } from "../../../lib/memory-repository";
import { MemoryPanel } from "./MemoryPanel";

type Auth = { user: { email?: string | null } | null; ready: boolean; configured: boolean; signInWithGoogle: () => Promise<void>; signOut: () => Promise<void> };

export function ResearchMemoryPanel({ memories, locale, auth, onSaveMemory, onDeleteMemory }: { memories: MemoryRecord[]; locale: HeatherLanguage; auth: Auth; onSaveMemory: (memory: MemoryRecord) => Promise<void>; onDeleteMemory: (id: string) => Promise<void> }) {
  const [scope, setScope] = useState<"private" | "team">("private");
  const [teams, setTeams] = useState<Team[]>([]); const [projects, setProjects] = useState<ResearchProject[]>([]);
  const [teamId, setTeamId] = useState(""); const [projectId, setProjectId] = useState("");
  const [teamMemories, setTeamMemories] = useState<MemoryRecord[]>([]); const [draft, setDraft] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState("");
  const repository = useMemo(() => new SupabaseMemoryRepository(), []); const copy = locale === "en" ? EN : KO;
  useEffect(() => { if (!auth.user) return; void repository.listTeams().then((next) => { setTeams(next); if (!teamId && next[0]) setTeamId(next[0].id); }).catch(() => setStatus(copy.loadFailed)); }, [auth.user, copy.loadFailed, repository, teamId]);
  useEffect(() => { if (!teamId) { setProjects([]); setProjectId(""); return; } void repository.listProjects(teamId).then((next) => { setProjects(next); setProjectId((current) => next.some((project) => project.id === current) ? current : next[0]?.id || ""); }).catch(() => setStatus(copy.loadFailed)); }, [repository, teamId, copy.loadFailed]);
  useEffect(() => { if (!teamId || !projectId) { setTeamMemories([]); return; } void repository.listTeamResearch(teamId, projectId).then(setTeamMemories).catch(() => setStatus(copy.loadFailed)); }, [repository, teamId, projectId, copy.loadFailed]);
  if (!auth.ready || !auth.user || scope === "private") return <section className="research-memory-mode"><ResearchMemoryTabs scope={scope} setScope={setScope} copy={copy} /><MemoryPanel variant="research" locale={locale} memories={memories} onSaveMemory={onSaveMemory} onDeleteMemory={onDeleteMemory} auth={auth} /></section>;
  const selectedTeam = teams.find((team) => team.id === teamId); const canEdit = selectedTeam?.role === "owner" || selectedTeam?.role === "editor";
  const filtered = teamMemories.filter((memory) => memory.content.toLowerCase().includes(query.toLowerCase()));
  async function createTeam() { const name = window.prompt(copy.teamName); if (!name?.trim()) return; const created = await repository.createTeam(name.trim()); setTeams((current) => [created, ...current]); setTeamId(created.id); }
  async function createProject() { if (!teamId) return; const name = window.prompt(copy.projectName); if (!name?.trim()) return; const created = await repository.createProject(teamId, name.trim()); setProjects((current) => [created, ...current]); setProjectId(created.id); }
  async function save() { if (!draft.trim() || !teamId || !projectId) return; const saved = await repository.saveTeamResearch({ id: createId("memory"), content: draft.trim(), created_at: nowIso(), updated_at: nowIso(), archived: false, confidence: .72, type: "project_context", source: "research", tags: [] }, teamId, projectId); setTeamMemories((current) => [saved, ...current]); setDraft(""); }
  return <section className="research-memory-mode"><ResearchMemoryTabs scope={scope} setScope={setScope} copy={copy} /><div className="team-memory-workspace"><header><div><h2>{copy.teamResearch}</h2><p>{copy.projectOnly}</p></div><div className="team-memory-selects"><select value={teamId} onChange={(event) => setTeamId(event.target.value)} aria-label={copy.team}>{teams.length ? teams.map((team) => <option key={team.id} value={team.id}>{team.name}</option>) : <option value="">{copy.noTeams}</option>}</select>{teams.length && !projects.length && canEdit ? <button type="button" onClick={() => void createProject()}><FolderPlus />{copy.createProject}</button> : null}{!teams.length ? <button type="button" onClick={() => void createTeam()}><Users />{copy.createTeam}</button> : null}<select value={projectId} onChange={(event) => setProjectId(event.target.value)} disabled={!projects.length} aria-label={copy.project}>{projects.length ? projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>) : <option value="">{copy.noProjects}</option>}</select></div></header>{!teams.length || !projects.length ? <div className="team-memory-empty"><Database /><h3>{!teams.length ? copy.noTeams : copy.noProjects}</h3><p>{!teams.length ? copy.teamEmpty : copy.projectEmpty}</p>{canEdit || !teams.length ? <button type="button" onClick={() => void (!teams.length ? createTeam() : createProject())}><Plus />{!teams.length ? copy.createTeam : copy.createProject}</button> : null}</div> : <div className="team-memory-body"><aside><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={copy.search} /></label><p>{copy.count(filtered.length)}</p>{filtered.map((memory) => <article key={memory.id}><strong>{memory.content}</strong><time>{new Intl.DateTimeFormat(locale === "en" ? "en-US" : "ko-KR", { month: "short", day: "numeric" }).format(new Date(memory.updated_at))}</time></article>)}</aside><main><h3>{copy.newNote}</h3><textarea value={draft} onChange={(event) => setDraft(event.target.value)} disabled={!canEdit} placeholder={canEdit ? copy.placeholder : copy.viewer} /><button type="button" onClick={() => void save()} disabled={!canEdit || !draft.trim()}>{copy.save}</button></main></div>}{status ? <p className="team-memory-status">{status}</p> : null}</div></section>;
}
function ResearchMemoryTabs({ scope, setScope, copy }: { scope: "private" | "team"; setScope: (scope: "private" | "team") => void; copy: typeof KO }) { return <nav className="research-memory-tabs"><button type="button" className={scope === "private" ? "is-active" : ""} onClick={() => setScope("private")}>{copy.privateResearch}</button><button type="button" className={scope === "team" ? "is-active" : ""} onClick={() => setScope("team")}>{copy.teamResearch}</button></nav>; }
const KO = { privateResearch: "개인 연구", teamResearch: "팀 연구", team: "연구팀", project: "연구 프로젝트", noTeams: "연구팀 없음", noProjects: "프로젝트 없음", createTeam: "연구팀 만들기", createProject: "프로젝트 만들기", teamName: "연구팀 이름", projectName: "연구 프로젝트 이름", teamEmpty: "팀 연구를 시작하려면 먼저 연구팀을 만드세요.", projectEmpty: "이 팀의 연구 프로젝트를 만들어 메모리를 분리하세요.", projectOnly: "선택한 연구팀과 프로젝트의 메모리만 표시합니다.", search: "프로젝트 메모리 검색", count: (count: number) => `${count}개 메모리`, newNote: "새 팀 연구 메모리", placeholder: "프로젝트 연구 내용을 입력하세요.", viewer: "Viewer는 메모리를 작성할 수 없습니다.", save: "저장", loadFailed: "팀 연구 데이터를 불러오지 못했습니다." };
const EN = { privateResearch: "Private research", teamResearch: "Team research", team: "Research team", project: "Research project", noTeams: "No research teams", noProjects: "No projects", createTeam: "Create team", createProject: "Create project", teamName: "Research team name", projectName: "Research project name", teamEmpty: "Create a research team to start team research.", projectEmpty: "Create a research project to keep its memories separate.", projectOnly: "Only memories for the selected team and project are shown.", search: "Search project memories", count: (count: number) => `${count} memories`, newNote: "New team research memory", placeholder: "Enter project research information.", viewer: "Viewers cannot write memories.", save: "Save", loadFailed: "Could not load team research data." };
