import type { MemoryRecord } from "@heather/core";
import { getSupabaseBrowserClient } from "./supabase-client";

export type Team = { id: string; name: string; description: string; role: "owner" | "editor" | "viewer" };
export type ResearchProject = { id: string; teamId: string; name: string; description: string; status: string };

export class SupabaseMemoryRepository {
  private client() { const client = getSupabaseBrowserClient(); if (!client) throw new Error("Supabase is not configured."); return client; }
  async listPersonal() { const { data, error } = await this.client().from("personal_memories").select("*").order("updated_at", { ascending: false }); if (error) throw error; return (data || []).map((row) => toMemory(row, "personal")); }
  async listPrivateResearch() { const { data, error } = await this.client().from("research_memories").select("*").eq("scope", "private").order("updated_at", { ascending: false }); if (error) throw error; return (data || []).map((row) => toMemory(row, "research")); }
  async listTeamResearch(teamId: string, projectId: string) { const { data, error } = await this.client().from("research_memories").select("*").eq("scope", "team").eq("team_id", teamId).eq("project_id", projectId).order("updated_at", { ascending: false }); if (error) throw error; return (data || []).map((row) => toMemory(row, "research")); }
  async savePersonal(memory: MemoryRecord) { return this.save("personal_memories", memory, { user_id: (await this.userId()), memory_type: memory.type }); }
  async savePrivateResearch(memory: MemoryRecord) { return this.save("research_memories", memory, { owner_id: (await this.userId()), scope: "private", memory_type: "project_context" }); }
  async saveTeamResearch(memory: MemoryRecord, teamId: string, projectId: string) { return this.save("research_memories", memory, { owner_id: (await this.userId()), scope: "team", team_id: teamId, project_id: projectId, memory_type: "project_context" }); }
  async deletePersonal(id: string) { const { error } = await this.client().from("personal_memories").delete().eq("id", id); if (error) throw error; }
  async deleteResearch(id: string) { const { error } = await this.client().from("research_memories").delete().eq("id", id); if (error) throw error; }
  async listTeams(): Promise<Team[]> { const { data, error } = await this.client().from("research_team_members").select("role, research_teams(id,name,description)").eq("status", "active"); if (error) throw error; return (data || []).flatMap((row: Record<string, unknown>) => { const team = row.research_teams as Record<string, unknown> | null; return team ? [{ id: String(team.id), name: String(team.name), description: String(team.description || ""), role: row.role as Team["role"] }] : []; }); }
  async listProjects(teamId: string): Promise<ResearchProject[]> { const { data, error } = await this.client().from("research_projects").select("id,team_id,name,description,status").eq("team_id", teamId).order("created_at", { ascending: false }); if (error) throw error; return (data || []).map((row) => ({ id: String(row.id), teamId: String(row.team_id), name: String(row.name), description: String(row.description || ""), status: String(row.status) })); }
  async createTeam(name: string, description = "") { const userId = await this.userId(); const { data, error } = await this.client().from("research_teams").insert({ name, description, owner_id: userId }).select("id,name,description").single(); if (error) throw error; return { id: String(data.id), name: String(data.name), description: String(data.description || ""), role: "owner" as const }; }
  async createProject(teamId: string, name: string, description = "") { const userId = await this.userId(); const { data, error } = await this.client().from("research_projects").insert({ team_id: teamId, name, description, created_by: userId }).select("id,team_id,name,description,status").single(); if (error) throw error; return { id: String(data.id), teamId: String(data.team_id), name: String(data.name), description: String(data.description || ""), status: String(data.status) }; }
  private async userId() { const { data } = await this.client().auth.getUser(); if (!data.user) throw new Error("Sign in is required."); return data.user.id; }
  private async save(table: "personal_memories" | "research_memories", memory: MemoryRecord, owner: Record<string, unknown>) { const row = { content: memory.content, title: null, summary: null, tags: memory.tags, metadata: {}, archived: memory.archived, ...owner }; const isExisting = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(memory.id); const query = isExisting ? this.client().from(table).update(row).eq("id", memory.id).select("*").single() : this.client().from(table).insert(row).select("*").single(); const { data, error } = await query; if (error) throw error; return toMemory(data, table === "personal_memories" ? "personal" : "research"); }
}

function toMemory(row: Record<string, unknown>, kind: "personal" | "research"): MemoryRecord { return { id: String(row.id), content: String(row.content), created_at: String(row.created_at), updated_at: String(row.updated_at), archived: Boolean(row.archived), confidence: .72, type: String(row.memory_type || (kind === "research" ? "project_context" : "important_fact")) as MemoryRecord["type"], source: kind, tags: Array.isArray(row.tags) ? row.tags.map(String) : [] }; }
